# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: destroyed-symlinks
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.29.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: eslint
        args: ['--fix']
        exclude: assets/js/github.js
        additional_dependencies:
          - eslint@8.6.0
          - eslint-config-google@0.7.1
          - babel-eslint@10.1.0
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - eslint-loader@1.6.1
-   repo: https://github.com/pre-commit/mirrors-scss-lint
    rev: 'v0.59.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: scss-lint
